# Basic colors
foreground           #BABABA
background           #222226
selection_foreground #d8dee9
selection_background #434c5e

# Cursor colors
cursor            #d8dee9
cursor_text_color #3b4252

# URL underline color when hovering with mouse
url_color #0087bd

# Window border colors and terminal bell colors
active_border_color   #81a1c1
inactive_border_color #4c566a
bell_border_color     #88c0d0
visual_bell_color     none

# Tab bar colors
active_tab_foreground   #3b4252
active_tab_background   #88c0d0
inactive_tab_foreground #e5e9f0
inactive_tab_background #4c566a
tab_bar_background      #3b4252
tab_bar_margin_color    none

# Mark colors (marked text in the terminal)
mark1_foreground #3b4252
mark1_background #88c0d0
mark2_foreground #3b4252
mark2_background #bf616a
mark3_foreground #3b4252
mark3_background #ebcb8b

# The basic 16 colors
## 1st : normal
## 2nd : bright
# black
color0 #000000
color8 #666666

# red
color1 #E8341C
color9 #E05A4F

# green
color2  #68C256
color10 #77B869

# yellow
color3  #F2D42C
color11 #EFD64B

# blue
color4  #1C98E8
color12 #387CD3

# magenta
color5  #8E69C9
color13 #957BBE

# cyan
color6  #1C98E8
color14 #3D97E2

# white
color7  #BABABA
color15 #BABABA

