## name: Tokyo Night
## license: MIT
## author: Folke Lemaitre
## upstream: https://github.com/folke/tokyonight.nvim/raw/main/extras/kitty/tokyonight_night.conf

[colors-dark]
background=1a1b26
foreground=c0caf5
selection-background=283457
selection-foreground=c0caf5
urls=73daca
cursor=1a1b26 c0caf5

# normal
regular0=15161e
regular1=f7768e
regular2=9ece6a
regular3=e0af68
regular4=7aa2f7
regular5=bb9af7
regular6=7dcfff
regular7=a9b1d6

# bright
bright0=414868
bright1=ff899d
bright2=9fe044
bright3=faba4a
bright4=8db0ff
bright5=c7a9ff
bright6=a4daff
bright7=c0caf5

## Misc colors
# jump-labels=<regular0> <regular3>          # black-on-yellow
# scrollback-indicator=<regular0> <bright4>  # black-on-bright-blue
# search-box-no-match=<regular0> <regular1>  # black-on-red
# search-box-match=<regular0> <regular3>     # black-on-yellow
