[module/xkeyboard]
type = internal/xkeyboard
; blacklist-0 = num lock

format = <label-indicator> <label-layout>

label-layout = %icon%
label-layout-foreground = ${colors.disabled}
layout-icon-default = UNK
layout-icon-0 = us;EN
layout-icon-1 = ir;FA

label-indicator-padding = 1
label-indicator-margin = 0
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

